### ISSUE TITLE
[BUG] サーバーでIFTTTブロックのTHENにJavaScriptを設定しようとしても登録できない

### ISSUE THREAD

**Issue by Saqliva** [Kai-Z-JP/ATSAssistMod#62]
# バグの詳細
- IFTTTブロックのTHENにJavaScriptを設定しようとしても設定できない(追加を押してもTHENに追加されない)
- サーバーはクラッシュしない(下記のログを吐き出すだけ)
- シングルではこのバグは発生しない
- 簡単なコード（importPackageをするだけ）でも発生する

<details>
<summary>サーバー/クライアント環境</summary>

## 共通
- CPU: Ryzen7 3700X
- OS: Win10 64bit 22H2
- Forge: 1614
- Minecraft: 1.7.10
- ATSAssist: 1.7.9
- mods: KaizPatchX 1.7.0, SignalController 1.4.0, etc...
## サーバー
- サーバーjar: Thermos 1614(似た環境でmohistでも同現象を確認)

</details>

<details>
<summary>現象発生時のサーバー側のログ</summary>

```
[04:38:43 WARN]: com.fasterxml.jackson.databind.JsonMappingException: net.minecraft.client.Minecraft at [Source: (byte[])"{"@class":"jp.kaiz.atsassistmod.ifttt.IFTTTContainer$That$ATSAssist$JavaScript","once":false,"jsText":"importPackage(Packages.jp.kaiz.atsassistmod.api);\nimportPackage(Packages.jp.kaiz.atsassistmod.utils);\nimportPackage(Packages.jp.ngt.rtm.electric);\nimportPackage(Packages.jp.ngt.ngtlib.util);\n\nimportPackage(Packages.jp.ngt.ngtlib.io);\n\nvar i = 0;\n\nfunction doThat(tile, train, first) {\n    var world = KaizTileEntityUtils.getWorld(tile);\n    var signals = [\n        [[-5672, 56, 679], ["[truncated 4656 bytes]; line: 1, column: 2652] (through reference chain: jp.kaiz.atsassistmod.ifttt.IFTTTContainer$That$ATSAssist$JavaScript["jstext"])
[04:38:43 WARN]:        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:276)
[04:38:43 WARN]:        at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:630)
[04:38:43 WARN]:        at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:618)
[04:38:43 WARN]:        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:143)
[04:38:43 WARN]:        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
[04:38:43 WARN]:        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:215)
[04:38:43 WARN]:        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
[04:38:43 WARN]:        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:170)
[04:38:43 WARN]:        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:136)
[04:38:43 WARN]:        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
[04:38:43 WARN]:        at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
[04:38:43 WARN]:        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
[04:38:43 WARN]:        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
[04:38:43 WARN]:        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3833)
[04:38:43 WARN]:        at jp.kaiz.atsassistmod.ifttt.IFTTTUtil.convertClassSafe(IFTTTUtil.java:30)
[04:38:43 WARN]:        at jp.kaiz.atsassistmod.network.PacketIFTTT.onMessage(PacketIFTTT.java:62)
[04:38:43 WARN]:        at jp.kaiz.atsassistmod.network.PacketIFTTT.onMessage(PacketIFTTT.java:12)
[04:38:43 WARN]:        at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37)
[04:38:43 WARN]:        at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17)
[04:38:43 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[04:38:43 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[04:38:43 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[04:38:43 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101)
[04:38:43 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[04:38:43 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[04:38:43 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[04:38:43 WARN]:        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[04:38:43 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[04:38:43 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[04:38:43 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[04:38:43 WARN]:        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[04:38:43 WARN]:        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
[04:38:43 WARN]:        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
[04:38:43 WARN]:        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181)[04:38:43 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023)
[04:38:43 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[04:38:43 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
[04:38:43 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[04:38:43 WARN]:        at java.lang.Thread.run(Unknown Source)
[04:38:43 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
[04:38:43 WARN]:        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[04:38:43 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[04:38:43 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[04:38:43 WARN]:        at jp.kaiz.atsassistmod.ifttt.IFTTTContainer$That$ATSAssist$JavaScript.setJSText(IFTTTContainer.java:979)
[04:38:43 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[04:38:43 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[04:38:43 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[04:38:43 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[04:38:43 WARN]:        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:141)
[04:38:43 WARN]:        ... 35 more
```
</details>

**Comment by Saqliva** [comment]
```
[04:38:43 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
```
って出てるし多分[IFTTTContainer.javaの979行目](https://github.com/Kai-Z-JP/ATSAssistMod/blob/e3860e2dd36abea7c8d29b060ccd653d83297595/src/main/java/jp/kaiz/atsassistmod/ifttt/IFTTTContainer.java#L979C7-L979C7)でclientを使ってるから落ちてる？
```java
public void setJSText(String jsText) {
  this.uuid = net.minecraft.client.Minecraft.getMinecraft().thePlayer.getUniqueID(); //ここ
  this.jsText = jsText;
  this.error = false;
}
```

**Comment by Saqliva** [comment]
↑だとしたら普通に今までのバージョンでも落ちてるわ

**Comment by Saqliva** [comment]
1.7.8、1.7.9は動かずに1.7.6だと普通に動くみたい（1.7.7は未検証）

**Comment by Kai-Z-JP** [comment]
eb52894d で修正
